require('./leveldown-test')
require('./abstract-leveldown-test')
require('./approximate-size-test')
require('./cleanup-hanging-iterators-test')
require('./compression-test')
require('./iterator-gc-test')
require('./iterator-recursion-test')
require('./port-libuv-fix-test')
require('./segfault-test')
require('./iterator-test')

//require('./destroy-test')
//require('./repair-test')
//require('./compact-range-test')
//require('./getproperty-test')
