freebsd_instance:
  image_family: freebsd-12-2

task:
  name: FreeBSD
  provision_script:
    - pkg install -y git node npm
  install_script:
    - git submodule update --init --recursive
    - env ELECTRON_SKIP_BINARY_DOWNLOAD=1 npm i --unsafe-perm
  test_script: npm t
