#!/bin/bash

set -ex

DOCKER_USER="node"

if [[ "$TRAVIS" == "true" ]]; then DOCKER_USER="travis"; fi

exec docker run -u ${DOCKER_USER} --rm -it -v $(pwd):/app prebuild/linux-armv7 \
     bash -c "npm i --ignore-scripts && npx prebuildify -t 8.14.0 --napi --strip"
